LeaveManagementt/Controllers/LeaveApplicationController.cs
using LeaveManagementt.Models;
using LeaveManagementt.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LeaveManagementt.Controllers
{
    public class LeaveApplicationController : Controller
    {
        // GET: LeaveApplication
        LeaveManagementDBEntities1 db = new LeaveManagementDBEntities1();

        public ActionResult Index()
        {
            List<Leave> leaves = db.Leaves.ToList();
            ViewBag.leaves = new SelectList(leaves, "LeaveId", "LeaveType");
            return View();
        }
        [HttpPost]
        public ActionResult ApplyLeave(LeaveDetail leaveDetail)
        {
            //if (!ModelState.IsValid)
            //{
            //    var viewModel = new LeaveViewModel
            //    {
            //        LeaveDetail = leaveDetail,
            //        Leaves = db.Leaves.ToList()
            //    };
            //}
            db.LeaveDetails.Add(leaveDetail);
            if (leaveDetail.Status == null)
            {
                leaveDetail.LeaveStatus = 1;
            }
            if (leaveDetail.TypeOfLeave == null)
            {
                leaveDetail.TypeOfLeave = 1;
            }

            db.SaveChanges();
            if (leaveDetail.Employee_Id == 2)

                return RedirectToAction("Index", "ManagingDirector");

            else
                return RedirectToAction("Index", "Supervisor");
        }
    }
}

LeaveManagementt/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @*<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>*@
                @*<ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Leave", "Index", "LeaveApplication")</li>
                    <li>@Html.ActionLink("Supervisor", "Index", "Supervisor")</li>
                    <li>@Html.ActionLink("MD", "Index", "ManagingDirector")</li>
                </ul>*@
                @Html.ActionLink("Leave Management", "Index", "Login", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @*<ul class="nav navbar-nav">
                <li>@Html.ActionLink("Leave", "Index", "LeaveApplication")</li>
                <li>@Html.ActionLink("Supervisor", "Index", "Supervisor")</li>
                <li>@Html.ActionLink("MD", "Index", "ManagingDirector")</li>
            </ul>*@
                @*@Html.Partial("_LoginPartial")*@
            </div>
            @*@Html.Partial("_LoginPartial")*@
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>